# Generated by Django 4.2.10 on 2024-03-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description_short', models.TextField()),
                ('description_long', models.TextField()),
                ('lng', models.DecimalField(decimal_places=15, max_digits=20)),
                ('lat', models.DecimalField(decimal_places=15, max_digits=20)),
            ],
        ),
    ]
