# Generated by Django 4.2.10 on 2024-03-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_tourimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourimage',
            name='position',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
