# Generated by Django 4.2.10 on 2024-03-14 12:08

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_tourcompany_options_alter_tourimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourcompany',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterModelOptions(
            name='tourimage',
            options={'ordering': ('position',), 'verbose_name': 'Фото локации', 'verbose_name_plural': 'Фото локаций'},
        ),
        migrations.RemoveField(
            model_name='tourcompany',
            name='description_long',
        ),
        migrations.RemoveField(
            model_name='tourcompany',
            name='description_short',
        ),
        migrations.AddField(
            model_name='tourcompany',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Подробное описание'),
        ),
        migrations.AddField(
            model_name='tourcompany',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='tourcompany',
            name='lat',
            field=models.DecimalField(decimal_places=15, max_digits=20, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='tourcompany',
            name='lng',
            field=models.DecimalField(decimal_places=15, max_digits=20, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='tourcompany',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='position',
            field=models.PositiveIntegerField(verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='tour_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.tourcompany', verbose_name='Локация'),
        ),
    ]
