# Generated by Django 4.2.10 on 2024-03-17 10:01

from django.db import migrations, models
from tinymce.models import HTMLField


def change_null_to_empty(apps, schema_editor):
    TourCompany = apps.get_model('places', 'TourCompany')
    TourCompany.objects.filter(short_description=None).update(short_description='')
    TourCompany.objects.filter(long_description=None).update(long_description='')


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_tourcompany_title'),
    ]

    operations = [
        migrations.RunPython(change_null_to_empty),
        migrations.AlterField(
            model_name='tourcompany',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Краткое описание', default=''),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='tourcompany',
            name='long_description',
            field=HTMLField(blank=True, verbose_name='Подробное описание', default=''),
            preserve_default=True,
        ),
    ]
