# Generated by Django 4.2.10 on 2024-03-17 16:51

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20240317_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourcompany',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='tourcompany',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
    ]
